### ISSUE TITLE
Missing temporal data

### ISSUE THREAD

**Issue by asadsabir** [CIOL-SUST/SupplyGraph#2]
I noticed that about 12 of the 40 products had only zeros for their temporal data. Is it supposed to be like that? It wasn’t mentioned in the paper. Any clarification would be greatly appreciated!

**Comment by azminewasi** [comment]
Yes, some products has very low production and demand; and it can be zero too.
But they are included, because they relate to other products of same group/sub-groups; as if the company choses to not to produce one or one product has less demand, the same product group's other products may have high demand/production.

We will release more information in coming months.
